export interface Condition {
  type: 'and' | 'or' | 'not' | 'simple';
  conditions?: Condition[];
  field?: string;
  operator?: 'eq' | 'ne' | 'gt' | 'lt' | 'gte' | 'lte' | 'contains' | 'in';
  value?: unknown;
}

export interface Action {
  type: 'device_command' | 'scene_execution' | 'notification' | 'delay';
  deviceId?: string;
  sceneId?: string;
  command?: string;
  parameters?: Record<string, unknown>;
  message?: string;
  delayMs?: number;
}

export interface Rule {
  id: string;
  name: string;
  description?: string;
  enabled: boolean;
  autoGenerated: boolean;
  priority: number;
  condition: Condition;
  actions: Action[];
  cooldownMs?: number;
  maxActivationsPerHour?: number;
  createdAt: Date;
  updatedAt: Date;
  lastExecuted?: Date;
  executionCount: number;
}

export interface RuleExecutionContext {
  userId?: string;
  deviceId?: string;
  timestamp: Date;
  data: Record<string, unknown>;
}

export interface SafetyCheckResult {
  safe: boolean;
  reason?: string;
  violations: string[];
}

export interface RuleEngineConfig {
  maxActivationsPerHour?: number;
  defaultCooldownMs?: number;
  maxExecutionTime?: number;
  enableSafetyChecks?: boolean;
}
